[package]
name = "snapi"
version = "0.1.0"
edition = "2021"
authors = ["Krzysztof Gał <dev@krzysztofgal.pl>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
